In [1]:
import numpy as np

# Numpy arrays from Python Lists 

In [2]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [3]:
[3.14, 2,3,4]

[3.14, 2, 3, 4]

In [4]:
np.array([3.14,2,3,4])

array([3.14, 2.  , 3.  , 4.  ])

In [5]:
np.array([1,2,3,4], dtype ="float32")

array([1., 2., 3., 4.], dtype=float32)

In [7]:
a1= np.array([[1,2,3],
             [4,5,6]])

In [8]:
type(a1)

numpy.ndarray

In [9]:
a1.shape

(2, 3)

In [10]:
#Số chiều của mãng
a1.ndim

2

In [11]:
a1.size

6

# Tạo Numpy arrays từ các hàm có sẳn Scratch

In [12]:
# Zero, ones, full, arange, línspace

In [16]:
np.zeros([10,9], dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [17]:
np.ones([3,5], dtype = float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [20]:
np.full([3,5], 8.2)

array([[8.2, 8.2, 8.2, 8.2, 8.2],
       [8.2, 8.2, 8.2, 8.2, 8.2],
       [8.2, 8.2, 8.2, 8.2, 8.2]])

In [21]:
np.linspace(0,1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

# Random

In [26]:
#seed
np.random.seed(0)
np.random.random([4,4])

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])

In [34]:
# np.random.normal( mean, độ lệch chuẩn, mãng )
np.random.normal(0,1,(3,3))

array([[-0.02818223,  0.42833187,  0.06651722],
       [ 0.3024719 , -0.63432209, -0.36274117],
       [-0.67246045, -0.35955316, -0.81314628]])

In [32]:
np.random.randint(5,7, (4,5))

array([[6, 6, 6, 6, 6],
       [5, 6, 6, 6, 6],
       [5, 6, 6, 5, 5],
       [6, 5, 5, 5, 5]])

In [36]:
np.random.rand(4,4)

array([[0.0641475 , 0.69247212, 0.56660145, 0.26538949],
       [0.52324805, 0.09394051, 0.5759465 , 0.9292962 ],
       [0.31856895, 0.66741038, 0.13179786, 0.7163272 ],
       [0.28940609, 0.18319136, 0.58651293, 0.02010755]])

# Array Indexing and Slicing

In [37]:
X1 = np.random.randint(20, size = 6)

In [38]:
X1

array([ 8, 13,  2,  3,  2, 11])

In [42]:
X1[4], X1[0], X1[-1]

(2, 8, 11)

In [44]:
X2 = np.random.randint(0, 10, (3,4))

In [45]:
X2

array([[0, 8, 8, 3],
       [8, 2, 8, 4],
       [3, 0, 4, 3]])

In [46]:
X2[1,2]

8

In [47]:
X2[1,2] = 9

In [48]:
X2

array([[0, 8, 8, 3],
       [8, 2, 9, 4],
       [3, 0, 4, 3]])

# Slicing

In [49]:
X1

array([ 8, 13,  2,  3,  2, 11])

In [60]:
X2[:2,:3]

array([[0, 8, 8],
       [8, 2, 9]])

In [61]:
#reshape of Array
grid = np.arange(1,10)
grid

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
X1[0:3]

array([ 8, 13,  2])

In [62]:
grid.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
X1[2:4]

array([2, 3])

In [67]:
# Transpose
X = np.array([[1,2], [3,4]])

In [68]:
X

array([[1, 2],
       [3, 4]])

In [53]:
X1[::2]

array([8, 2, 2])

In [69]:
X.T

array([[1, 3],
       [2, 4]])

# Ghép  và Tách Array

In [54]:
X2

array([[0, 8, 8, 3],
       [8, 2, 9, 4],
       [3, 0, 4, 3]])

In [70]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [71]:
np.concatenate((x,y))

array([1, 2, 3, 4, 5, 6])

In [74]:
grid = np.array([[1,2,3], [4,5,6]])
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [76]:
np.concatenate((grid,grid)) # axis = 0 by default

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [77]:
np.concatenate((grid,grid), axis =1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [55]:
X2[:2,:3]

array([[0, 8, 8],
       [8, 2, 9]])

In [80]:
#vstack
np.vstack((x,grid))

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [83]:
#hstack
y = np.array([[99] , [99]])
np.hstack((y,grid))

array([[99,  1,  2,  3],
       [99,  4,  5,  6]])

In [84]:
# Spliting
x = np.array([1,2,3,99,69,3,2,1])

In [86]:
X1, X2, X3 = np.split(x, (3,5))

In [88]:
X1 , X2 , X3

(array([1, 2, 3]), array([99, 69]), array([3, 2, 1]))

# Broadcasting and Vectorized operations

In [2]:
a= np.arange(0,3,1)

In [3]:
a

array([0, 1, 2])

In [4]:
a+5 #broadcasting

array([5, 6, 7])

In [7]:
b = np.ones((3,3))

In [8]:
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
a.shape, b.shape

((3,), (3, 3))

In [10]:
b+a

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [16]:
a*b # khong phai nhan ma tran

array([[0., 1., 2.],
       [0., 1., 2.],
       [0., 1., 2.]])

In [25]:
c = np.arange(3).reshape((3,1))

In [26]:
c

array([[0],
       [1],
       [2]])

In [27]:
a+c

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

# Manipulating & Comparing Arrays

In [28]:
# Aggregation
x = np.array((1,2,3))

In [29]:
x

array([1, 2, 3])

In [30]:
sum(x) # python sum

6

In [32]:
np.sum(x) #numpy sum

6

In [40]:
max_array = np.random.random(10000)
max_array[:10]
max_array.shape

(10000,)

In [41]:
%timeit sum(max_array)
%timeit np.sum(max_array) 

707 μs ± 30.5 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
6.5 μs ± 420 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [42]:
np.mean(max_array)

0.5041135119663465

In [43]:
np.max(max_array)

0.9999730042110389

In [44]:
np.min(max_array)

7.883645622541735e-06

In [46]:
# Variance la Phuong sai (Xichma^2)
# Standard Deviation la do lech chuan (Xichma)

In [48]:
dog_height = np.array([600,470,170,430,300])
np.std(dog_height)
# do lech chuan

147.32277488562318

In [ ]:
 np.var(dog_height)

In [50]:
np.sqrt(np.var(dog_height))

147.32277488562318

# Shorting arrays

In [52]:
x = np.array([1,2,6,7,3,8,9,2,5,9])
np.sort(x)

array([1, 2, 2, 3, 5, 6, 7, 8, 9, 9])

In [53]:
# argsort sort ra index
np.argsort(x)

array([0, 1, 7, 4, 8, 2, 3, 5, 6, 9], dtype=int64)

In [55]:
np.random.seed(42)
MatA = np.random.randint(0,10, size = (4,6))
MatA

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [57]:
np.sort(MatA, axis = 0)

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [58]:
np.sort(MatA, axis = 1)

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

# Linear Algebra

In [62]:
A = np.arange(1,10).reshape((3,3))

In [63]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [68]:
B = np.arange(10,16).reshape((3,2))

In [69]:
B

array([[10, 11],
       [12, 13],
       [14, 15]])

In [70]:
A.dot(B)

array([[ 76,  82],
       [184, 199],
       [292, 316]])

In [71]:
A@B

array([[ 76,  82],
       [184, 199],
       [292, 316]])

In [77]:
B.T@A

array([[156, 192, 228],
       [168, 207, 246]])

# Dot product example

In [79]:
np.random.seed(0)

sales_amounts = np.random.randint(20, size = (5,3))
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [81]:
import pandas as pd

weely_sales = pd.DataFrame(sales_amounts, index = ["Mon" ,"Tue" ,'Wed', 'Thurs', 'Fri'], 
                           columns = ['Almond Butter', 'Peanut Butter', 'Cashew Butter'])
weely_sales

Almond Butter  Peanut Butter  Cashew Butter
Mon               12             15              0
Tue                3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [86]:
# create a price array

prices = np.array([10,8,12])
prices.shape

(3,)

In [87]:
butter_price = pd.DataFrame(prices.reshape(1,3), index = ['Price'], 
                            columns = ['Almond Butter', 'Peanut Butter', 'Cashew Butter'])
butter_price

Almond Butter  Peanut Butter  Cashew Butter
Price             10              8             12

In [88]:
weely_sales.shape, butter_price.shape

((5, 3), (1, 3))

In [89]:
total_price = weely_sales.dot(butter_price.T)

In [90]:
total_price

Price
Mon      240
Tue      138
Wed      458
Thurs    232
Fri      142

In [91]:
weely_sales['Total_price'] = total_price

In [92]:
weely_sales

Almond Butter  Peanut Butter  Cashew Butter  Total_price
Mon               12             15              0          240
Tue                3              3              7          138
Wed                9             19             18          458
Thurs              4              6             12          232
Fri                1              6              7          142